import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {runStrategyScenario} from '../assets/strategy-engine.js';

const json=async path=>JSON.parse(await readFile(new URL(`../${path}`,import.meta.url),'utf8'));
const series=history=>Array.isArray(history.series)?history.series:history.seriesRows.map(values=>Object.fromEntries(history.seriesColumns.map((column,index)=>[column,values[index]])));
const closeTo=(actual,expected,tolerance=1e-6)=>assert.ok(Math.abs(Number(actual)-Number(expected))<=tolerance,`${actual} differs from ${expected} by more than ${tolerance}`);

test('summary exposes the fixed hub contract backed by non-fixture data',async()=>{const [summary,history,dashboard,strategy]=await Promise.all([json('data/summary.json'),json('data/history.json'),json('data/dashboard.json'),json('data/strategy-comparison.json')]);assert.equal(summary.schemaVersion,1);assert.equal(summary.contract,'quant-research-summary');assert.equal(summary.projectId,'fearngreed');assert.equal(summary.methodologyVersion,'fear-flow-v4');assert.ok(['ok','degraded','stale','unavailable'].includes(summary.status.state));assert.equal(history.fixture,false);assert.notEqual(dashboard.fixture,true);assert.ok(summary.dataAsOf<=summary.generatedAt.slice(0,10));assert.equal(summary.dataAsOf,history.dataAsOf);assert.equal(summary.dataAsOf,dashboard.dataAsOf);assert.equal(summary.dataAsOf,strategy.dataAsOf);assert.equal(summary.payload.strategyComparisonUrl,'./strategy-comparison.json');assert.equal(strategy.contract,'fearngreed-strategy-comparison');});
test('public json stays within size budgets and contains no secret canaries',async()=>{for(const [file,limit] of [['summary.json',50_000],['dashboard.json',500_000],['history.json',2_000_000],['strategy-comparison.json',500_000],['automation-status.json',50_000]]){const text=await readFile(new URL(`../data/${file}`,import.meta.url),'utf8');assert.ok(Buffer.byteLength(text)<limit);assert.doesNotMatch(text,/KRX_(API_KEY|ID|PW)|gho_|password/i);}});
test('strategy comparison publishes the dynamic browser control and explicit synthetic-short caveats',async()=>{const strategy=await json('data/strategy-comparison.json');assert.equal(strategy.methodologyVersion,'fear-flow-v4');assert.deepEqual(strategy.dynamicExitControl,{defaultLongExitPercentile:80,minimum:50,maximum:94,step:1,shortExitFormula:'100-longExitPercentile',calculationLocation:'browser_on_server_published_history_and_adjusted_prices',regressionRefit:true,signalEngineVersion:'browser-past-only-rolling-v1',scenarioAuthority:'browser_user_scenario_not_canonical_server_output',configurableInputs:{lookback:{default:252,minimum:60,maximum:756,step:1},minimumR2:{default:0.2,minimum:0,maximum:0.8,step:0.05},extremeTail:{default:5,minimum:1,maximum:20,step:1},maxHolding:{default:20,minimum:1,maximum:60,step:1}},minimumTrainingObservationsFormula:'min(lookback,max(40,min(200,ceil(lookback*0.8))))',pastOnly:true,evaluationRangeSeparate:true});assert.equal(strategy.policyDefinitions.longCash.policyId,'long_cash');assert.equal(strategy.policyDefinitions.longCash.shortEntry,null);assert.equal(strategy.policyDefinitions.longShortCash.policyId,'long_short_cash');assert.equal(strategy.policyDefinitions.longShortCash.shortabilityModeled,false);assert.equal(strategy.policyDefinitions.longShortCash.borrowFeeAnnualPct,0);for(const ticker of ['226490','069500']){const proxy=strategy.proxies[ticker];assert.ok(proxy);for(const period of ['fullPeriod','commonPeriod']){for(const cost of [0,5,10,20]){const result=proxy[period][`robust_${cost}bp`];assert.equal(result.policyId,'long_short_cash');assert.equal(result.longExitPercentile,80);assert.equal(result.shortExitPercentile,20);assert.ok(['long','short','cash'].includes(result.position));}}}});
test('browser engine default 80 path matches server-verified common-period results',async()=>{const [history,dashboard,strategy]=await Promise.all([json('data/history.json'),json('data/dashboard.json'),json('data/strategy-comparison.json')]);const historyRows=series(history);for(const ticker of ['226490','069500']){for(const [policyId,expected] of [['long_cash',dashboard.backtests.proxies[ticker].commonPeriod.robust_10bp],['long_short_cash',strategy.proxies[ticker].commonPeriod.robust_10bp]]){const actual=runStrategyScenario({historyRows,proxy:ticker,period:'common',variant:'scaled_huber',costBps:10,policyId,longExitPercentile:80});assert.equal(actual.metrics.start,expected.metrics.start);assert.equal(actual.metrics.end,expected.metrics.end);assert.equal(actual.policyId,expected.policyId);assert.equal(actual.position,expected.position);assert.equal(actual.pendingAction,expected.pendingAction);assert.equal(actual.pendingReason,expected.pendingReason);assert.equal(actual.pendingSide,expected.pendingSide);assert.equal(actual.metrics.tradeCount,expected.metrics.tradeCount);assert.equal(actual.metrics.longTradeCount,expected.metrics.longTradeCount);assert.equal(actual.metrics.shortTradeCount,expected.metrics.shortTradeCount);closeTo(actual.metrics.totalReturn,expected.metrics.totalReturn);closeTo(actual.metrics.longExposure,expected.metrics.longExposure,5e-10);closeTo(actual.metrics.shortExposure,expected.metrics.shortExposure,5e-10);const expectedTrades=expected.trades.map(({side,entry_date,exit_date,reason})=>({side,entry_date,exit_date,reason}));const actualTail=expectedTrades.length?actual.trades.slice(-expectedTrades.length):[];const actualTrades=actualTail.map(({side,entry_date,exit_date,reason})=>({side,entry_date,exit_date,reason}));assert.deepEqual(actualTrades,expectedTrades);}}});
test('static page labels limitations and research status',async()=>{const html=await readFile(new URL('../index.html',import.meta.url),'utf8');assert.match(html,/사후적·탐색적 연구 신호/);assert.match(html,/사건 검증/);assert.match(html,/투자 권유 아님/);});
