import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {runStrategyScenario} from '../assets/strategy-engine.js';

const json=async path=>JSON.parse(await readFile(new URL(`../${path}`,import.meta.url),'utf8'));
const series=history=>Array.isArray(history.series)?history.series:history.seriesRows.map(values=>Object.fromEntries(history.seriesColumns.map((column,index)=>[column,values[index]])));
const closeTo=(actual,expected,tolerance=1e-6)=>assert.ok(Math.abs(Number(actual)-Number(expected))<=tolerance,`${actual} differs from ${expected} by more than ${tolerance}`);

test('summary exposes the fixed hub contract backed by non-fixture data',async()=>{const [summary,history,dashboard,strategy]=await Promise.all([json('data/summary.json'),json('data/history.json'),json('data/dashboard.json'),json('data/strategy-comparison.json')]);assert.equal(summary.schemaVersion,1);assert.equal(summary.contract,'quant-research-summary');assert.equal(summary.projectId,'fearngreed');assert.equal(summary.methodologyVersion,'fear-flow-v5');assert.ok(['ok','degraded','stale','unavailable'].includes(summary.status.state));assert.equal(history.fixture,false);assert.notEqual(dashboard.fixture,true);assert.ok(summary.dataAsOf<=summary.generatedAt.slice(0,10));assert.equal(summary.dataAsOf,history.dataAsOf);assert.equal(summary.dataAsOf,dashboard.dataAsOf);assert.equal(summary.dataAsOf,strategy.dataAsOf);assert.equal(summary.payload.strategyComparisonUrl,'./strategy-comparison.json');assert.equal(strategy.contract,'fearngreed-strategy-comparison');});
test('public json stays within size budgets and contains no secret canaries',async()=>{for(const [file,limit] of [['summary.json',50_000],['dashboard.json',500_000],['history.json',2_000_000],['strategy-comparison.json',500_000],['automation-status.json',50_000]]){const text=await readFile(new URL(`../data/${file}`,import.meta.url),'utf8');assert.ok(Buffer.byteLength(text)<limit);assert.doesNotMatch(text,/KRX_(API_KEY|ID|PW)|gho_|password/i);}});
test('strategy comparison publishes dynamic controls and four actual ETF paths',async()=>{const strategy=await json('data/strategy-comparison.json');assert.equal(strategy.methodologyVersion,'fear-flow-v5');assert.deepEqual(strategy.dynamicExitControl,{defaultLongExitPercentile:80,minimum:50,maximum:94,step:1,shortExitFormula:'100-longExitPercentile',inverseExitFormula:'100-longExitPercentile',calculationLocation:'browser_on_server_published_history_and_adjusted_prices',regressionRefit:true,signalEngineVersion:'browser-past-only-rolling-v1',scenarioAuthority:'browser_user_scenario_not_canonical_server_output',configurableInputs:{lookback:{default:196,minimum:60,maximum:756,step:1},minimumR2:{default:0.4,minimum:0,maximum:0.8,step:0.05},extremeTail:{default:2,minimum:1,maximum:20,step:1},maxHolding:{default:20,minimum:1,maximum:60,step:1}},minimumTrainingObservationsFormula:'min(lookback,max(40,min(200,ceil(lookback*0.8))))',pastOnly:true,evaluationRangeSeparate:true});assert.equal(strategy.policyDefinitions.longInverseCash.policyId,'long_inverse_cash');assert.equal(strategy.policyDefinitions.longInverseCash.positionAccounting,'positive_listed_etf_units_no_synthetic_short');assert.equal(strategy.actualEtfPairs.authority,'canonical_server_verified_actual_etfs');assert.equal(strategy.actualEtfPairs.commonPeriod.status,'ok');assert.deepEqual(strategy.actualEtfPairs.commonPeriod.tickers,['069500','114800','122630','252670']);for(const [pairId,longTicker,inverseTicker,leverage] of [['1x','069500','114800',1],['2x','122630','252670',2]]){const result=strategy.actualEtfPairs.pairs[pairId];assert.equal(result.status,'ok');assert.equal(result.pair.longTicker,longTicker);assert.equal(result.pair.inverseTicker,inverseTicker);assert.equal(result.pair.leverage,leverage);for(const policyId of ['long_cash','long_inverse_cash']){const policy=result.policies[policyId];assert.equal(policy.policyId,policyId);assert.equal(policy.longExitPercentile,80);assert.equal(policy.inverseExitPercentile,20);assert.equal(policy.metrics.shortExposure,0);assert.ok(['long','inverse','cash'].includes(policy.position));assert.ok(policy.trades.every(trade=>trade.side!=='short'));}}});
test('browser engine default 80 path matches server-verified common-period results',async()=>{const [history,dashboard,strategy]=await Promise.all([json('data/history.json'),json('data/dashboard.json'),json('data/strategy-comparison.json')]);const historyRows=series(history);for(const ticker of ['226490','069500']){for(const [policyId,expected] of [['long_cash',dashboard.backtests.proxies[ticker].commonPeriod.robust_10bp],['long_short_cash',strategy.proxies[ticker].commonPeriod.robust_10bp]]){const actual=runStrategyScenario({historyRows,proxy:ticker,period:'common',variant:'scaled_huber',costBps:10,policyId,longExitPercentile:80});assert.equal(actual.metrics.start,expected.metrics.start);assert.equal(actual.metrics.end,expected.metrics.end);assert.equal(actual.policyId,expected.policyId);assert.equal(actual.position,expected.position);assert.equal(actual.pendingAction,expected.pendingAction);assert.equal(actual.pendingReason,expected.pendingReason);assert.equal(actual.pendingSide,expected.pendingSide);assert.equal(actual.metrics.tradeCount,expected.metrics.tradeCount);assert.equal(actual.metrics.longTradeCount,expected.metrics.longTradeCount);assert.equal(actual.metrics.shortTradeCount,expected.metrics.shortTradeCount);closeTo(actual.metrics.totalReturn,expected.metrics.totalReturn);closeTo(actual.metrics.longExposure,expected.metrics.longExposure,5e-10);closeTo(actual.metrics.shortExposure,expected.metrics.shortExposure,5e-10);const expectedTrades=expected.trades.map(({side,entry_date,exit_date,reason})=>({side,entry_date,exit_date,reason}));const actualTail=expectedTrades.length?actual.trades.slice(-expectedTrades.length):[];const actualTrades=actualTail.map(({side,entry_date,exit_date,reason})=>({side,entry_date,exit_date,reason}));assert.deepEqual(actualTrades,expectedTrades);}}});
test('static page leads with usable research outputs and keeps non-advice copy in closed operations detail',async()=>{const html=await readFile(new URL('../index.html',import.meta.url),'utf8');assert.match(html,/<section id="conclusion"/);assert.match(html,/<section id="evidence"/);assert.match(html,/<section id="strategy"/);const method=html.match(/<details class="card research-details" id="method">([\s\S]*?)<\/details>\s*<\/main>/)?.[1]??'';assert.match(method,/투자 권유 아님/);assert.doesNotMatch(html,/<header id="overview"[\s\S]*?투자 권유 아님[\s\S]*?<\/header>/);});
